### ISSUE TITLE
Support for proplist encoding

### ISSUE THREAD

**Issue by michaelklishin** [lpil/thoas#15]
This is a question as much as an issue report. We are trying to swap JSX for Thoas in RabbitMQ
and observed that Thoas does not encode proplists, even though the input type spec suggests that it should:

``` erl
thoas:encode(#{a => 1}).
```

succeeds but

``` erl
thoas:encode(maps:to_list(#{a => 1})).
```

fails with a function clause. Is this limitation by design?

**Comment by lpil** [comment]
Oh dear, sounds like a mistake. Let's add support for that

**Comment by lpil** [comment]
A couple questions:

Is not encoding proplists a problem for you?

Encoding an empty proplist would produce `[]` rather than `{}`, I presume that is OK?

**Comment by michaelklishin** [comment]
Yes, RabbitMQ HTTP API encodes a lot of values that come as proplists. Some of these subsystems predate Erlang maps by nearly a decade, so it's not realistic for us to change.

Empty proplist is an edge case we had to special case in several places. I would completely
understand if Thoas decided to not handle it. We can't realistically know if an empty list is
a, well, list, or an empty proplist that should be a JSON object. So it should be fine for us.

**Comment by michaelklishin** [comment]
We currently use JSX and this is how it encodes an empty list by default:

``` erl
jsx:encode([]).
%% => <<"[]">>
```

**Comment by the-mikedavis** [comment]
It looks like JSX detects proplists by matching on [`[{_, _} | _]`](https://github.com/talentdeficit/jsx/blob/1d3407aa9752430ec0a06111ac1b046ffafdca22/src/jsx_encoder.erl#L54). I can take a look at making a PR for this 🙂

**Comment by lpil** [comment]
v0.3.0 is out. https://hex.pm/packages/thoas/0.3.0

Thanks @michaelklishin & @the-mikedavis ! 💜
