### ISSUE TITLE
couple of small issues

### ISSUE THREAD

**Issue by leonardb** [lpil/thoas#6]
Firstly, great work.

Examples on README show incorrect output since you're using `lists` as keys/values

```
1> thoas:encode(#{"age" => 44, "name" => "Steve Irwin", "nationality" => "Australian"}).
<<"{\"age\":44,\"name\":[83,116,101,118,101,32,73,114,119,105,110],\"nationality\":[65,117,115,116,114,97,108,105,97,110]}">>
2> thoas:encode(#{<<"age">> => 44, <<"name">> => <<"Steve Irwin">>, <<"nationality">> => <<"Australian">>}).
<<"{\"age\":44,\"name\":\"Steve Irwin\",\"nationality\":\"Australian\"}">>
```

`null` is not being included as null in output (probably since Elixir uses `nil` whereas in Erlang we generally use `null` and that's the only case being matched
```
5> thoas:encode(#{dev => nil, dev2 => null}).                                                                           
<<"{\"dev\":null,\"dev2\":\"null\"}">>
```

See:
https://github.com/lpil/thoas/pull/7

**Comment by lpil** [comment]
Thank you for the report. I've fixed the README, let's talk about the rest in the PR.
